_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10  # RUDO has 10 classes
DATASETS:
  TRAIN: ("rudo_train_sparse_50_30",)
  TEST: ("rudo_test",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
SOLVER:
  STEPS: (30000, 33000)
  MAX_ITER: 35000
  IMS_PER_BATCH: 4
  BASE_LR: 0.0025
# 水下增强相关配置
UNDERWATER_ENHANCEMENT: True
UNDERWATER_ENHANCEMENT_WEIGHT: 0.1
OUTPUT_DIR: "SparseDet/experiments_rudo/sparse_50_30_underwater" 